### ISSUE TITLE
Review surveys conducted during Summer of Data Wufoo and update Connect Chicago detail pages accordingly

### ISSUE THREAD

**Issue by srobbin** [smartchicago/connect-chicago-locator#33]
Reassigned to @GovInTrenches 

All of the results of the Summer of Data surveys are found in the .csv titled. "Connect Chicago Summer of Data Form", which is found in the project folder.

There are 201 surveys, and they are rich with information. It's important to make sure that no private information is published. Look out for important details that would give residents a deeper understanding of the place as they plan a trip to that location.

**Comment by GovInTrenches** [comment]
First pass through done. Some notes: 

_These locations do not exist:_

http://locations.weconnectchicago.org/location/cares-chicago-3333-w-arthington-suite-139 (Admin office for another location)
http://locations.weconnectchicago.org/location/south-shore-library-2505-e-73rd-street (Branch Closed) 
http://locations.weconnectchicago.org/location/center-of-higher-development---archer-courts-2242-south-princeton (Not Public, Apt building guests only)
http://locations.weconnectchicago.org/location/center-of-higher-development---uptown-927-w-wilson (Only for tenants) 
http://locations.weconnectchicago.org/location/instituto-del-progreso-latino-at-st-michaels-education-center-2315-w-24th-place (Not Public)
http://locations.weconnectchicago.org/location/ntrc-homan-square--charles-h-shaw-technology-and-learning-center-3517-w-arthington-st (Not longer public)

I'll delete these off the board once I get the superuser access. 

_Things that need changing_  

http://locations.weconnectchicago.org/location/worknet-development-office-ctc-2610-w-north-ave-2nd-flr/edit (Phone disconnected) 

_Things we need to audit_ 

Many of the training programs don't exist because they were only being funded by BTOP. I'll start going through all the training things and making sure what's still current.

**Comment by srobbin** [comment]
Hi Christopher,

You have superadmin access now. Sorry it's taken so long to get that for you.

–Scott

**Comment by GovInTrenches** [comment]
No worries! Thanks a bunch!

**Comment by GovInTrenches** [comment]
Working on this bit by bit - should have this finished up shortly.

**Comment by GovInTrenches** [comment]
This has been done
